### PR TITLE
add issue template for incoming data request

### PR DESCRIPTION
**Pull request by uwe-salomon**
As requested by the CSMIM working group, here is a new issue template that could be used for requesting that other systems send data that is required by the issuer's system. For cases like in issue #9.

### CODE REVIEW

**Comment by matthias-heinisch** [comment]
Thank you for this template. Let's encourage usage of checklists with the template, so that we can track progress and easier close these probably long term collections once completed.

I will make a proposal.

**Review by matthias-heinisch — APPROVED** [review]

**Comment by uwe-salomon** [comment]
Note that you can try out the current issue templates at https://github.com/uwe-salomon/csmim-issue-templates/issues/new/choose

**Review by ravishankar-hcltech — COMMENTED** [review]
Thank you Uwe, this is helpful. 

Slightly added some formatting to your content. Please review them when you get a chance.

---

# Request Data from Other Subsystem(s)

> Use this template to request data from other subsystems not yet covered by existing CSMIM object types.

| Label | Enhancement |
| ----- | ----------- |

## Request Summary

**Describe for which equipment and intended usage you need additional data:**

Provide a clear, concise description

## Basic Information

| Field           | Value                                                   |
| --------------- | ------------------------------------------------------- |
| ATA Chapter     | e.g., 33-20: Lights / Passenger Compartment             |
| Security Domain | - [ ] Crew<br>- [ ] Passenger<br>- [ ] Other (specify): |

## Existing Types

**List existing types if they are related but fail to meet your needs:**

- [ ] No related existing types
- [ ] Related types (list below):
  - 1.
  - 2.

## Required Data Items

**List the additional data items you require from other subsystems:**

| Data Item Title  | Source System | Update Frequency                                     | Accuracy Requirements | Format/Units    |
| ---------------- | ------------- | ---------------------------------------------------- | --------------------- | --------------- |
| e.g., Cabin Temp | e.g., ECS     | - [ ] Real-time<br>- [ ] Periodic<br>- [ ] On-demand | e.g., ±0.5°C          | e.g., °C, float |
|                  |               | - [ ] Real-time<br>- [ ] Periodic<br>- [ ] On-demand |                       |                 |
|                  |               | - [ ] Real-time<br>- [ ] Periodic<br>- [ ] On-demand |                       |                 |

## Additional Requirements

**Please specify any other requirements not covered above:**

**Comment by uwe-salomon** [comment]
Hi Ravi,

thank you very much for your contribution!
As we already discussed quickly:

- I think elaborate formatting is not necessary. The template is just meant to make the issue creator think about some basics and provide a rough overview for anyone opening an issue.
- Using the checkboxes to provide choices is a good idea, but creates a task list in GitHub. The issue would then have a subheading "N tasks", with every check box counting as a task. But we could never close the tasks (because just one update frequency would be selected, for example). The way the issue template is now, tasks are only created for the data items. This enables us to check them when we have taken care of them, until all data items are checked and the issue can be closed.
- I'd rather that we propose the resource data type and the unit, instead of letting the issue creator do it. Typically, we want to enforce SI units and use plain integers or floating point values.

Is that acceptable for you?

**Review by DennisWhetten-Boeing — APPROVED** [review]

**Pull request merged**
